# Generated by Django 5.0 on 2023-12-24 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок к фотографии'),
        ),
    ]
