# Generated by Django 5.0 on 2023-12-24 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='partner',
            field=models.BooleanField(default=True, help_text='Партнер (если True то локации ему будет отправляться)', verbose_name='Партнер'),
        ),
    ]
